cfp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import django.conf.urls.i18n

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('chart.urls', namespace='chart'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chart/urls.py
from django.urls import path
from .views import index, results

app_name = 'chart'

urlpatterns = [
    path('', index, name='index'),
    path('results', results, name='results'),

]

chart/models.py
from django.db import models

# Create your models here.

chart/views.py
from django.shortcuts import render
from django.utils import translation
from .utils import get_y
from django.views.decorators.http import require_POST


def index(request):
    # if "lang" in request.GET:
    #     translation.activate(request.GET.get("lang"))

    return render(request, 'base.html')


@require_POST
def results(request):
    gas = None
    temperature = None
    pressur = None
    if request.method == 'POST':
        pressur = int(request.POST.get('pressure'))
        temperature = int(request.POST.get('temperature'))
        gas = get_y(x=pressur, ser='1/8')
        print(pressur, temperature, gas)
    context = {'pressure': pressur, 'temperature': temperature, 'gas': gas}
    return render(request, 'results.html', context=context)

templates/base.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="CFP charts" />
    <meta name="CFP" content="CFP charts" />
    <meta name="generator" content="Hugo 0.80.0" />
    <title>CFP</title>
    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css"
      integrity="sha384-JvExCACAZcHNJEc7156QaHXTnQL3hQBixvj5RV5buE7vgnNEzzskDtx9NQ4p6BJe"
      crossorigin="anonymous"
    />
    <meta name="theme-color" content="#7952b3" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body class="bg-light">
    <section id="signIn">
<div class="container mt-3 text-center">
            <form  action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input name="next" type="hidden" value="{% url 'chart:index' %}">
                <select name="language" id="langs">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                          {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
                {% comment %} <input type="submit" value="Go"> {% endcomment %}
            </form>
</div>


      <div class="container">
        <div class="row">
          <div class="col-12 col-md-7 col-lg-5 mt-5 mx-auto text-center">
            <h1 id="bigLogo" class="text-primary">
              <a href="#"
                >{% trans "حاسب الغاز" %}<img class="mb-2" src="imgs/logo-icon2.svg" alt=""
              /></a>
            </h1>
          </div>
        </div>
        <div class="row">
          <div class="col-12 col-md-7 col-lg-5 my-3 mx-auto">
            <div class="bg-white rounded">
              <h5 class="blockHeading p-3 text-center text-primary">
              {% trans "حاسب الغاز" %}
              </h5>
              <form class="p-4" method="POST" action="{% url 'chart:results'  %}"">
                {% csrf_token %}

                <label for="press" class="form-label">{% trans "قيمه الضغط المقاس" %}</label>
                <input
                  type="text"
                  name="pressure"
                  class="form-control"
                  id="press"
                  required
                />

                <label for="temp" class="form-label"
                  > {% trans "قيمه الحراره المقاسه" %}</label
                >
                <input
                  type="text"
                  name="temperature"
                  class="form-control"
                  id="temp"
                  required
                />
                <label for="orificefd" class="form-label">{% trans "مقاس الاورفيس" %}</label>
                <select name="orifice" id="orificefd" class="form-control">
                  <option value="0.125">1/8</option>
                  <option value=".250">1/4</option>
                  <option value="0.375">3/8</option>
                  <option value=".5">1/2</option>
                  <option value=".750">3/4</option>
                </select>
                <button type="submit" class="btn btn-primary mt-3 w-100">
                  {% trans "أحسب" %}
                </button>
              </form>

            </div>
          </div>
        </div>
        <div class="row"></div>
      </div>
    </section>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.rtlcss.com/bootstrap/v4.5.3/js/bootstrap.min.js"
      integrity="sha384-VmD+lKnI0Y4FPvr6hvZRw6xvdt/QZoNHQ4h5k0RL30aGkR9ylHU56BzrE2UoohWK"
      crossorigin="anonymous"
    ></script>

<script>
$(document).ready(function() {
  $('#langs').on('change', function() {
     this.form.submit();
  });
});
</script>

  </body>
</html>

templates/results.html
{% load static %} {% load i18n %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="CFP charts" />
    <meta name="CFP" content="CFP charts" />
    <meta name="generator" content="Hugo 0.80.0" />
    <title>CFP</title>
    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css"
      integrity="sha384-JvExCACAZcHNJEc7156QaHXTnQL3hQBixvj5RV5buE7vgnNEzzskDtx9NQ4p6BJe"
      crossorigin="anonymous"
    />
    <meta name="theme-color" content="#7952b3" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body class="bg-light">
    <section id="signIn">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-7 col-lg-5 mt-5 mx-auto text-center">
            <h1 id="bigLogo" class="text-primary">
              <a href="{% url 'chart:index'  %}"
                >{% trans "حاسب الغاز" %}<img
                  class="mb-2"
                  src="imgs/logo-icon2.svg"
                  alt=""
              /></a>
            </h1>
          </div>
        </div>
        <div class="row">
          <div class="col-12 col-md-7 col-lg-5 my-3 mx-auto">
            <div class="bg-white rounded">
              <h5 class="blockHeading p-3 text-center text-primary">
                {% trans "تقرير النتائج" %}
              </h5>
              <form class="p-4" method="POST" id="myform">
                {% csrf_token %}
                <input type="hidden" name="alert" value="{{alert}}" readonly />

                <label for="press" class="form-label"
                  >{% trans "قيمه الضغط المقاس" %}</label
                >
                <input
                  type="text"
                  name="pressure"
                  value="{{pressure}}"
                  class="form-control"
                  id="press"
                  disabled
                />

                <label for="temp" class="form-label"
                  >{% trans "قيمه الحراره المقاسه" %}</label
                >
                <input type="text" name="temperature" class="form-control"
                value="{{temperature}}"" id="temp" disabled />
                <label for="orificefd" class="form-label"
                  >{% trans "مقاس الاورفيس" %}
                </label>
                <select name="orifice" id="orificefd" class="form-control">
                  <option value="0.125" selected>1/8</option>
                </select>

                {% if gas%}

                <label for="temp" class="form-label"
                  >{% trans "قيمه الغاز المحسوبه" %}</label
                >
                <input
                  type="text"
                  name="temperature"
                  class="form-control"
                  id="temp"
                  value="{{gas|floatformat:2}}"
                  disabled
                />
                {% else %}

                <label for="temp" class="form-label">
                  {% trans "قيمه الغاز المحسوبه" %}</label
                >
                <input type="text" name="temperature" class="form-control"
                id="temp" value="{% trans "القيم خارج نطاق البيانات" %}"
                disabled /> {% endif %}
              </form>
            </div>
          </div>
        </div>
        <div class="row"></div>
      </div>
    </section>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.rtlcss.com/bootstrap/v4.5.3/js/bootstrap.min.js"
      integrity="sha384-VmD+lKnI0Y4FPvr6hvZRw6xvdt/QZoNHQ4h5k0RL30aGkR9ylHU56BzrE2UoohWK"
      crossorigin="anonymous"
    ></script>
  </body>
</html>